version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secretmongo
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
